name: Docker Image CI

on: 
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - name: Build and Publish the Docker image
      env: 
        BUILD_ID: ${{ job.container.id }}
        REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
      run: |
        docker login docker.pkg.github.com --username LytvyniukDima --password $REGISTRY_TOKEN
        docker build . --file Dockerfile -t englishlearning-tasks:1.$BUILD_ID
        docker tag englishlearning-tasks:1.$BUILD_ID docker.pkg.github.com/lytvyniukdima/englishLearning.taskService/englishlearning-tasks:latest
        docker tag englishlearning-tasks:1.$BUILD_ID docker.pkg.github.com/lytvyniukdima/englishLearning.taskService/englishlearning-tasks:1.$BUILD_ID
        docker push docker.pkg.github.com/lytvyniukdima/englishLearning.taskService/englishlearning-tasks:latest
        docker push docker.pkg.github.com/lytvyniukdima/englishLearning.taskService/englishlearning-tasks:1.$BUILD_ID
